### ISSUE TITLE
¿Evaluar que tan buenas son las predicciones del modelo?

### ISSUE THREAD

**Issue by MarcosPalacios** [MarcosPalacios/Recurrent-Neural-Networks-for-Electricity-Price-Prediction#2]
No termino de ver como saber si los modelos que estoy probando son buenos o malos.  @Javier-Pardo @alabarga 

El notebook mas reciente es el hecho en Colab, con el mejor modelo.

**Comment by alabarga** [comment]
![imagen](https://user-images.githubusercontent.com/166339/127452910-8791d1df-fa93-42a4-a085-c5ace7ce320d.png)
estas predicciones estan bastante bien, no?
